-- Add missing Settings columns (idempotent)
ALTER TABLE "Settings"
  ADD COLUMN IF NOT EXISTS "tone" TEXT NOT NULL DEFAULT 'neutral',
  ADD COLUMN IF NOT EXISTS "goal" TEXT NOT NULL DEFAULT 'complete_checkout',
  ADD COLUMN IF NOT EXISTS "max_call_seconds" INTEGER NOT NULL DEFAULT 120,
  ADD COLUMN IF NOT EXISTS "max_followup_questions" INTEGER NOT NULL DEFAULT 2,

  ADD COLUMN IF NOT EXISTS "discount_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "max_discount_percent" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "offer_rule" TEXT NOT NULL DEFAULT 'ask_only',
  ADD COLUMN IF NOT EXISTS "min_cart_value_for_discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "coupon_prefix" TEXT NOT NULL DEFAULT 'OFFER',
  ADD COLUMN IF NOT EXISTS "coupon_validity_hours" INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS "free_shipping_enabled" BOOLEAN NOT NULL DEFAULT FALSE,

  ADD COLUMN IF NOT EXISTS "followup_email_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "followup_sms_enabled" BOOLEAN NOT NULL DEFAULT TRUE;